/*This file was generated by Makina. Do not modify.*/

static int oven_idle(struct oven *, struct oven_event *);
static int oven_cooking(struct oven *, struct oven_event *);
static int oven_open(struct oven *, struct oven_event *);

static int oven_idle(struct oven *self, struct oven_event *event) {
	if (!self || !event) return -1;
	if (event.id == oven_start && true) {
		self->state = oven_cooking;
		enable_heater(self, event);
		return 0;
	}
	if (event.id == oven_open && true) {
		self->state = oven_open;
		return 0;
	}
	return 0;
}

static int oven_cooking(struct oven *self, struct oven_event *event) {
	if (!self || !event) return -1;
	if (event.id == oven_timeout && true) {
		disable_heater(self, event);
		self->state = oven_idle;
		return 0;
	}
	if (event.id == oven_open && true) {
		disable_heater(self, event);
		self->state = oven_open;
		return 0;
	}
	return 0;
}

static int oven_open(struct oven *self, struct oven_event *event) {
	if (!self || !event) return -1;
	if (event.id == oven_close && true) {
		self->state = oven_idle;
		return 0;
	}
	if (event.id == oven_start && true) {
		error(self, event);
		return 0;
	}
	return 0;
}

int oven_init(struct oven *self) {
	if (!self) return -1;
	self->state = oven_idle;
	return 0;
}

int oven_process_event(struct oven *self, struct oven_event *event) {
	if (!self || !event) return -1;
	if (!self->state) return -1;
	self->state(self, event);
	return 0;
}

