/*This file was generated by Makina. Do not modify.*/
#ifndef OVEN_H
#define OVEN_H

struct oven;
struct oven_event;

int enable_heater(struct oven *, struct oven_event *);
int disable_heater(struct oven *, struct oven_event *);
int error(struct oven *, struct oven_event *);

enum oven_event_id {
	oven_event_start,
	oven_event_timeout,
	oven_event_open,
	oven_event_close,
};

struct oven_event {
	enum oven_event_id id;
	void *ctx;
};

struct oven {
	int (*state)(struct oven *, struct oven_event *);
	void *ctx;
};

int oven_init(struct oven *);

int oven_process_event(struct oven *, struct oven_event *);

#endif /*OVEN_H*/
