/*This file was generated by Makina. Do not modify.*/
#include "oven.h"

static int oven_closed_idle(struct oven *, struct oven_event *);
static int oven_closed_cooking(struct oven *, struct oven_event *);
static int oven_open(struct oven *, struct oven_event *);

static int oven_closed_idle(struct oven *self, struct oven_event *event) {
	if (!self || !event) return -1;
	if (event->id == oven_event_start && 1) {
		self->state = oven_closed_cooking;
		enable_heater(self, event);
		return 0;
	}
	if (event->id == oven_event_open && 1) {
		self->state = oven_open;
		return 0;
	}
	return 0;
}

static int oven_closed_cooking(struct oven *self, struct oven_event *event) {
	if (!self || !event) return -1;
	if (event->id == oven_event_timeout && 1) {
		disable_heater(self, event);
		self->state = oven_closed_idle;
		return 0;
	}
	if (event->id == oven_event_open && 1) {
		disable_heater(self, event);
		self->state = oven_open;
		return 0;
	}
	return 0;
}

static int oven_open(struct oven *self, struct oven_event *event) {
	if (!self || !event) return -1;
	if (event->id == oven_event_close && 1) {
		self->state = oven_closed_idle;
		return 0;
	}
	if (event->id == oven_event_start && 1) {
		error(self, event);
		return 0;
	}
	return 0;
}

int oven_init(struct oven *self) {
	if (!self) return -1;
	self->state = oven_closed_idle;
	return 0;
}

int oven_process_event(struct oven *self, struct oven_event *event) {
	if (!self || !event) return -1;
	if (!self->state) return -1;
	self->state(self, event);
	return 0;
}
