/*This file was generated by Makina. Do not modify.*/

static int Turnstile_Closed(struct Turnstile *, struct Turnstile_event *);
static int Turnstile_Open(struct Turnstile *, struct Turnstile_event *);

static int Turnstile_Closed(struct Turnstile *self, struct Turnstile_event *event) {
	if (!self || !event) return -1;
	if (event.id == Turnstile_ticket && Closed_valid_ticket(self, event)) {
		return 0;
	}
	if (event.id == Turnstile_ticket && true) {
		Closed_notify_invalid_ticket(self, event);
		return 0;
	}
	if (event.id == Turnstile_pass && true) {
		Closed_alarm(self, event);
		return 0;
	}
	return 0;
}

static int Turnstile_Open(struct Turnstile *self, struct Turnstile_event *event) {
	if (!self || !event) return -1;
	if (event.id == Turnstile_pass && true) {
		return 0;
	}
	if (event.id == Turnstile_ticket && true) {
		Open_return_ticket(self, event);
		return 0;
	}
	return 0;
}

int Turnstile_init(struct Turnstile *self) {
	if (!self) return -1;
	self->state = Turnstile_Closed;
	Closed_apply_latch(self, NULL);
	return 0;
}

int Turnstile_process_event(struct Turnstile *self, struct Turnstile_event *event) {
	if (!self || !event) return -1;
	if (!self->state) return -1;
	self->state(self, event);
	return 0;
}

